//
// Simple playground for the EBML writer.
// Right now it just generates a WebM file with a header for two streams. No real data in there.
//

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "../ebml_writer.h"


int main(){
	FILE* f = fopen("test.webm", "wb");
	
	off_t o1, o2, o3, o4;
	
	o1 = ebml_element_start(f, MKV_EBML);
		ebml_element_string(f, MKV_DocType, "webm");
	ebml_element_end(f, o1);
	
	// Should actually be an element with unknown size but the ebml viewer program
	// can't handle it. Therefore disabled for easier debugging.
	//ebml_element_start_unkown_data_size(f, MKV_Segment);
	o1 = ebml_element_start(f, MKV_Segment);
		o2 = ebml_element_start(f, MKV_Info);
			ebml_element_uint(f, MKV_TimecodeScale, 1000000);
			ebml_element_string(f, MKV_MuxingApp, "smeb v0.1");
			ebml_element_string(f, MKV_WritingApp, "smeb v0.1");
		ebml_element_end(f, o2);
		
		o2 = ebml_element_start(f, MKV_Tracks);
			// Video track
			o3 = ebml_element_start(f, MKV_TrackEntry);
				ebml_element_uint(f, MKV_TrackNumber, 1);
				ebml_element_uint(f, MKV_TrackUID, 1);
				ebml_element_uint(f, MKV_TrackType, MKV_TrackType_Video);
				
				ebml_element_string(f, MKV_CodecID, "V_VP8");
				// These were not included in files generated by mkclean
				//ebml_element_uint(f, MKV_FlagEnabled, 1);
				//ebml_element_uint(f, MKV_FlagDefault, 1);
				//ebml_element_uint(f, MKV_FlagForced, 1);
				ebml_element_uint(f, MKV_FlagLacing, 1);
				ebml_element_string(f, MKV_Language, "und");
				
				o4 = ebml_element_start(f, MKV_Video);
					ebml_element_uint(f, MKV_PixelWidth, 720);
					ebml_element_uint(f, MKV_PixelHeight, 576);
					ebml_element_uint(f, MKV_DisplayWidth, 768);
					ebml_element_uint(f, MKV_DisplayHeight, 576);
					ebml_element_uint(f, MKV_DisplayUnit, MKV_DisplayUnit_DisplayAspectRatio);
				ebml_element_end(f, o4);
				
			ebml_element_end(f, o3);
			
			// Audio track
			o3 = ebml_element_start(f, MKV_TrackEntry);
				ebml_element_uint(f, MKV_TrackNumber, 1);
				ebml_element_uint(f, MKV_TrackUID, 1);
				ebml_element_uint(f, MKV_TrackType, MKV_TrackType_Video);
				
				ebml_element_string(f, MKV_CodecID, "A_VORBIS");
				ebml_element_uint(f, MKV_FlagLacing, 1);
				ebml_element_string(f, MKV_Language, "ger");
				
				o4 = ebml_element_start(f, MKV_Audio);
					ebml_element_float(f, MKV_SamplingFrequency, 48000);
					ebml_element_uint(f, MKV_Channels, 2);
					ebml_element_uint(f, MKV_BitDepth, 16);
				ebml_element_end(f, o4);
				
			ebml_element_end(f, o3);
			
		ebml_element_end(f, o2);
		
	ebml_element_end(f, o1);
	
	fclose(f);
}